"""initial_migration

Revision ID: 5d8c7ceaf044
Revises: 
Create Date: 2026-07-23 12:39:48.927379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8c7ceaf044'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_risk_score', sa.Float(), nullable=True),
    sa.Column('last_risk_class', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_hostname'), 'machines', ['hostname'], unique=True)
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.create_table('remediation_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('command_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('issued_by', sa.String(), nullable=True),
    sa.Column('reboot_required', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_commands_hostname'), 'remediation_commands', ['hostname'], unique=False)
    op.create_index(op.f('ix_remediation_commands_id'), 'remediation_commands', ['id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('smb_v1_enabled', sa.Boolean(), nullable=True),
    sa.Column('rdp_enabled', sa.Boolean(), nullable=True),
    sa.Column('autorun_enabled', sa.Boolean(), nullable=True),
    sa.Column('open_network_shares', sa.Boolean(), nullable=True),
    sa.Column('macro_execution_enabled', sa.Boolean(), nullable=True),
    sa.Column('powershell_unrestricted', sa.Boolean(), nullable=True),
    sa.Column('uac_disabled', sa.Boolean(), nullable=True),
    sa.Column('applocker_absent', sa.Boolean(), nullable=True),
    sa.Column('defender_disabled', sa.Boolean(), nullable=True),
    sa.Column('firewall_disabled', sa.Boolean(), nullable=True),
    sa.Column('tamper_protection_off', sa.Boolean(), nullable=True),
    sa.Column('event_logging_disabled', sa.Boolean(), nullable=True),
    sa.Column('admin_shares_enabled', sa.Boolean(), nullable=True),
    sa.Column('lsass_protection_off', sa.Boolean(), nullable=True),
    sa.Column('guest_account_active', sa.Boolean(), nullable=True),
    sa.Column('vss_deleted', sa.Boolean(), nullable=True),
    sa.Column('backup_absent', sa.Boolean(), nullable=True),
    sa.Column('bitlocker_off', sa.Boolean(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_class', sa.String(), nullable=True),
    sa.Column('flagged_parameters', sa.String(), nullable=True),
    sa.Column('prev_risk_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_id'), 'scans', ['id'], unique=False)
    op.create_index(op.f('ix_scans_machine_id'), 'scans', ['machine_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_machine_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_remediation_commands_id'), table_name='remediation_commands')
    op.drop_index(op.f('ix_remediation_commands_hostname'), table_name='remediation_commands')
    op.drop_table('remediation_commands')
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_index(op.f('ix_machines_hostname'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
